---
- name: install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755
  become: yes
  tags: install-docker-compose

